<a href="https://colab.research.google.com/github/julianovale/DATA_DataSciencePython/blob/main/Aula07_DataSciencePython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução à Data Science com Python - Data ICMC-USP

Esse material foi desenvolvido pelo Data, grupo de extensão de aprendizado e ciência de dados compostos por alunos do Instituto de Ciências Matemáticas e de Computação da USP.

Esse notebook é acompanhado de um curso em video, que pode ser encontrado em [aqui](https://www.youtube.com/playlist?list=PLFE-LjWAAP9SfEuLXf3qrpw4szKWjlYq9)

Para saber mais sobre as atividades do Data entre no nosso site e nos siga e nossas redes sociais:
- [Site](http://data.icmc.usp.br/)
- [Twitter](https://twitter.com/data_icmc)
- [LinkedIn](https://www.linkedin.com/school/data-icmc/)
- [Facebook](https://www.facebook.com/dataICMC/)

Aproveite o material!


## NumPy

NumPy é uma biblioteca para manipulação de vetores e matrizes, possuindo várias funções para lidar com esses dados. A biblioteca é muito eficiente e é usada como base para diversar outras bibliotecas de ciência de dados em Python. Iremos ver o material básico importante de NumPy, mas é muito recomendado conferir a documentação oficial em https://numpy.org/doc/, lá é possível encontrar exemplos de uso para todas as funcionalidades da biblioteca. 

In [4]:
# É comum importar o numpy o chamando só de np 
import numpy as np

### Arrays

Arrays são a generalização de vetores e matrizes com qualquer número de dimensões. O `np.array` é o elemento central do NumPy, e é com eles que precisamos saber trabalhar.

Como foi dito, um array numpy pode ter qualquer número de dimenções, vamos observar os exemplos na imagem a baixo:

<img src="https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png">

([fonte da imagem](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html))

Certo, então é possível ver que os arrays tem uma dimensão e uma tamanho em cada uma dessas dimenções. Cada dimensão é identificada por um eixo (*axis*) como podemos ver na imagem.

Vamos trabalhar com um exemplo simples:

In [ ]:
# Vamos criar nosso primeiro array
a = np.array([2, 3, 5, 7, 11])
a

array([ 2,  3,  5,  7, 11])

In [ ]:
# O atributo ndim do array guarda seu número de dimenções
a.ndim

1

In [ ]:
# O shape (formato) do array é um atributo ainda mais importante
a.shape

(5,)

In [ ]:
# Podemos acessar um entrada do array como fizemos com listas
a[2]

5

In [ ]:
# Podemos também alterar uma entrada do array
a[3] = 42
a

array([ 2,  3,  5, 42, 11])

Tudo que fizemos aqui funciona para qualquer número de dimensões, vamos ver:

In [ ]:
# Criando uma matriz
b = np.array([[10, 20], 
              [30, 40], 
              [50, 60]])
b

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
# Visualizando número de dimensões e shape
print(b.ndim)
print(b.shape)

2
(3, 2)


In [ ]:
# Agora precisamos informar a posição em cada eixo para acessar elementos
b[2, 1]

60

In [ ]:
# Também podemos mudar entradas
b[1, 0] = 23
b

array([[10, 20],
       [23, 40],
       [50, 60]])

**Pergunta:** Qual o shape de uma imagem em tons de cinza de tamanho 200x200? E de uma imagem RGB do mesmo tamanho?

<img src="https://github.com/julianovale/DATA_DataSciencePython/blob/main/img/img_array.png?raw=true">

Tons de cinza: (200, 200) => 2D

Colorida: (200, 200, 3) => 3D

### Gerando arrays
Até aqui criamos todos nossos arrays definindo valores na mão utilizando listas em Python. Porém o NumPy possui funções convenientes para criar novos arrays

In [ ]:
# Cria um array só com zeros com shape (2,2)
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
# Cria um array só com uns com shape (2,2)
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [ ]:
# Cria um array de shape (3,2) com valores aleatórios
a = np.random.random((3,2))
a

array([[0.08588102, 0.13070642],
       [0.77185667, 0.81529719],
       [0.53934995, 0.86400365]])

In [ ]:
# Cria um array com valores aleatorios inteiros (20 é o valor maxímo)
a = np.random.randint(20, size=(3,2))
a

array([[14,  2],
       [11,  2],
       [13, 19]])

In [ ]:
# Cria um vetor de 0 a 4
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

Não temos tempo de ver todas as funções desse tipo que existem, tente dar uma olhada em `np.zeros_like`, `np.full`, `np.linspace`, entre outras.

### Operações matemáticas

Até agora pode não ter ficado muito claro o motivo de estarmos usando arrays do NumPy ao invés de usar simplesmente listas nativas do Python. A vantagem está justamente nas várias operações suportadas por arrays. Vamos ver alguns exemplos

In [ ]:
# Vamos criar um vetor aleatorio que iremos utilizar
a = np.random.randint(10, size=(5,))
a

array([8, 9, 3, 8, 7])

In [ ]:
# Podemos realizar varias operaçoes

print(a + 10) # Soma

print(a - 4) # Subtração

print(a * 3) # Multiplicação

print(a / 2) # Divisão

print(a ** 2) # Exponenciação

print(a < 5) # Comparação

[18 19 13 18 17]
[ 4  5 -1  4  3]
[24 27  9 24 21]
[4.  4.5 1.5 4.  3.5]
[64 81  9 64 49]
[False False  True False False]


Também podemos realizar operações entre arrays

In [ ]:
# Vamos criar dois vetores aleatorios que iremos utilizar
a = np.random.randint(10, size=(5,))
b = np.random.randint(10, size=(5,))

print(a)
print(b)

[1 0 9 7 2]
[4 7 2 4 4]


In [ ]:
# Podemos realizar soma (ou subtração) elemento a elemento
print(a + b)

[ 5  7 11 11  6]


In [ ]:
# Também podemos realizar multiplicação (ou divisão) elemento a elemento
print(a * b)

[ 4  0 18 28  8]


In [ ]:
# Para isso é muito importante que os shapes sejam iguais
c = np.random.randint(10, size=(7,))
print(a + c)

ValueError: ignored

In [ ]:
# Também temos operações como o produto escalar entre os vetores
np.dot(a, b)

58

Lembre-se que tudo isso também vale para matrizes

In [ ]:
# Vamos criar duas matrizes aleatorias que iremos utilizar
a = np.random.randint(10, size=(3,4))
b = np.random.randint(10, size=(3,4))

print(a)
print('-----')
print(b)

[[6 2 5 3]
 [2 1 5 7]
 [4 7 6 2]]
-----
[[1 8 4 5]
 [4 0 1 9]
 [4 9 6 1]]


In [ ]:
# Operações com escalares
print(a + 100)
print('-----')
print(a * 3)

[[106 102 105 103]
 [102 101 105 107]
 [104 107 106 102]]
-----
[[18  6 15  9]
 [ 6  3 15 21]
 [12 21 18  6]]


In [ ]:
# Somando matrizes elemento a elemento
print(a + b)

[[ 7 10  9  8]
 [ 6  1  6 16]
 [ 8 16 12  3]]


In [ ]:
# Podemos transpor uma matriz
print(b)
print(b.T)

[[1 8 4 5]
 [4 0 1 9]
 [4 9 6 1]]
[[1 4 4]
 [8 0 9]
 [4 1 6]
 [5 9 1]]


In [ ]:
# Podemos multiplicar matrizes
# (com np.dot, np.multiply é multiplicação elemento a elemento)
c = np.random.randint(10, size=(4, 4))
print(a)
print('-------')
print(c)
print('Shapes:', a.shape, c.shape)
print(np.dot(a, c))

[4 0 6 0]
-------
[[2 5 6 2]
 [0 0 4 1]
 [5 2 6 9]
 [1 6 5 0]]
Shapes: (4,) (4, 4)
[38 32 60 62]


Podemos fazer operações entre vetores e matrizes. De forma geral isso é chamado de *broadcasting*, mas vamos nos limitar a um caso simples

In [ ]:
# Criando nosso vetor e nossa matriz
a = np.random.randint(10, size=(4,))
b = np.random.randint(20, size=(3,4))

print(a)
print() # Imprime linha em branco entre eles
print(b)

[8 9 9 5]

[[ 5 17 18 17]
 [ 0  8 12 19]
 [13 16  2 19]]


In [ ]:
# Isso tem o efeito de subtrair cada linha da matriz pelo vetor
b - a

array([[-3,  8,  9, 12],
       [-8, -1,  3, 14],
       [ 5,  7, -7, 14]])

### Funções importantes

#### Funções de agregação

In [ ]:
# Vamos criar um vetor que iremos utilizar
a = np.random.randint(20, size=(5,))
print(a)

[15  0  4  2  7]


In [ ]:
# Soma
np.sum(a) # ou a.sum()

28

In [ ]:
# Média
np.mean(a) # ou a.mean()

5.6

Temos várias outras como `np.median`, `np.std`, `np.max`, `np.min`,...

Isso também funciona com matrizes normalmente, mas também temos a opção de agregar por eixo

In [ ]:
# Vamos criar uma matriz que iremos utilizar
a = np.random.randint(10, size=(3, 4))
print(a)

[[6 2 0 1]
 [1 2 4 0]
 [3 0 8 3]]


In [ ]:
# Podemos somar toda a matriz
np.sum(a)

30

In [ ]:
# Podemos somar as linhas
np.sum(a, axis=1)

array([ 9,  7, 14])

In [ ]:
# Podemos somar as colunas
np.sum(a, axis=0)

array([10,  4, 12,  4])

#### Reshape
Essa é uma função que nos permite alterar a shape de arrays

In [ ]:
# Vamos criar um vetor que iremos utilizar
a = np.random.randint(20, size=(18,))
print(a)

[16 14 13 13 13  7  2 16 19  5  6 12  0 17  1 18  9 13]


In [ ]:
# Tranformar em matriz 9 por 2
b = a.reshape(9, 2)
print(b)

c = a.reshape(2,9)
print(c)

[[16 14]
 [13 13]
 [13  7]
 [ 2 16]
 [19  5]
 [ 6 12]
 [ 0 17]
 [ 1 18]
 [ 9 13]]
[[16 14 13 13 13  7  2 16 19]
 [ 5  6 12  0 17  1 18  9 13]]


In [ ]:
# Tranformar em matriz 3 por 6
c = a.reshape(3, 6)
c

array([[16, 14, 13, 13, 13,  7],
       [ 2, 16, 19,  5,  6, 12],
       [ 0, 17,  1, 18,  9, 13]])

In [ ]:
# Tranformar em tensor 3D 3 por 2 por 3
d = a.reshape(3, 2, 3)
d

array([[[16, 14, 13],
        [13, 13,  7]],

       [[ 2, 16, 19],
        [ 5,  6, 12]],

       [[ 0, 17,  1],
        [18,  9, 13]]])

### Indexação

#### Arrays 1D

In [5]:
# Vamos criar um vetor que iremos utilizar
a = np.random.randint(20, size=(10,))
print(a)

[ 2  8  9  2  0 13  6 14 12  1]


In [6]:
# Como já vimos podemos indexar exatamente como no Python puro
print(a[4])
print(a[5:8])

0
[13  6 14]


In [7]:
# Podemos indexar usando um lista dos valores que queremos
print(a[[0, 2, 3]])

[2 9 2]


In [8]:
# Podemos também indexar usando valores booleanos
print(a[[False, True, False, False, False, True, True, False, True, True]])

[ 8 13  6 12  1]


In [9]:
# A indexação com booleanos é muito util combinado com comparação
maior_que_10 = a > 10
print(maior_que_10)
b = a[maior_que_10]
print(b)

[False False False False False  True False  True  True False]
[13 14 12]


#### Arrays 2D

In [14]:
a = np.random.randint(50, size=(4,6))
print(a)

[[36 20  5 33 21 48]
 [ 8 13 22  4 11 35]
 [ 5 24 47  0 42 45]
 [ 6 12  7 16 21 13]]


In [15]:
# Podemos acessar elementos unicos informando a posição em cada eixo
print(a[2, 4])

42


In [16]:
# Podemos fatiar um pedaço da matriz fatiando em cada eixo
print(a[1:3, 2: 5])

[[22  4 11]
 [47  0 42]]


In [17]:
# Utilizar : sozinho significa que queros todos os valores do eixo em questão
print(a[:, 2]) # Todas linhas da coluna 2
print(a[1, :]) # Todas as colunas da linha 1
print(a[1, 2:4]) # Colunas 2 e 3 da linha 1 

[ 5 22 47  7]
[ 8 13 22  4 11 35]
[22  4]


In [18]:
# Podemos realizar a indexação por booleanos também (mas vira 1D)
a[a > 25]

array([36, 33, 48, 35, 47, 42, 45])

Esses conceitos são totalmente iguais para qualquer número de dimensões.

**Pergunta:** Como podemos extrair apenas o canal verde de uma imagem RGB?


**Minha resposta:** green = imagem[ : , : , 1]


### Velocidade

In [20]:
a = [[j for j in range(10000)] for _ in range(1000)]
b = np.array(a)
b

array([[   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       ...,
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999]])

In [23]:
%%time
for i in range(len(a)):
    for j in range(len(a[0])):
        a[i][j] *= 10

CPU times: user 1.54 s, sys: 5.09 ms, total: 1.54 s
Wall time: 1.55 s


In [24]:
%%time
b *= 10

CPU times: user 16.2 ms, sys: 0 ns, total: 16.2 ms
Wall time: 18.8 ms
